### ISSUE TITLE
No back arrow to navigate back on Phone Usage screen/Find Icon Quiz

### ISSUE THREAD

**Issue by jemooh** [brianmwadime/Mozilla-DSO-Quiz-Application#4]

**Comment by secretrobotron** [comment]
Marking as part of QA bug squashing in MozillaFoundation/digital-skills-observatory#215.

**Comment by secretrobotron** [comment]
@brianmwadime is this fixed already?

**Comment by brianmwadime** [comment]
Uploading an update with this fixed.

**Comment by brianmwadime** [comment]
@secretrobotron This is fixed.
